### ISSUE TITLE
Serve pre-compiled JavaScript for browsers

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno_registry2#269] opened 2021-12-03 12:39 UTC
I want to be able to use Deno modules written in TypeScript directly from a browser without using Deno bundling.

See https://github.com/denoland/deno_std/issues/641#issuecomment-739518201.

This way great modules like from the standard library and others can be used and cached browser-side as an alternative to bundling. Probably most useful for one-off cases as bundling is probably still best for larger clients but for small use cases a direct import may be ideal.

**Comment by crowlKats** [comment] 2021-12-03 12:47
Duplicate of https://github.com/denoland/dotland/issues/1728

**Closed by crowlKats** 2021-12-03 12:47 UTC
